Couchbase Alerts
SumoLogic/terraform-sumologic-sumo-logic-monitor pull request #59
Opened 2022-01-21 05:09 UTC by PhuNguyenMTT

2022-01-25 07:21 UTC, arunpatyal requested changes

2022-01-25 09:37 UTC, PhuNguyenMTT commented on monitor_packages/Couchbase/couchbase.json
> +      "name": "Couchbase - Too Many Login Failure",
updated

2022-01-25 09:37 UTC, PhuNguyenMTT commented on monitor_packages/Couchbase/couchbase.tf
> +  monitor_name                = "Couchbase - Too Many Login Failure"
updated

2022-01-25 10:26 UTC, arunpatyal commented
We are using the same variable for critical, warning and missing data, this generates error if customer specifies critical connection or email action. Need to make changes as per this [PR](https://github.com/SumoLogic/terraform-sumologic-sumo-logic-monitor/pull/49).

2022-02-12 13:54 UTC, PhuNguyenMTT commented
i updated for variables for critical, warning and missing data

2022-02-14 13:53 UTC, merged